version: '3.9'

networks:
  chatnetwork:
    driver: bridge

services:
  server:
    image: server
    container_name: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 8000:8000
    networks:
      - chatnetwork

  client01:
    image: client
    container_name: client01
    build:
      context: .
      dockerfile: ./client/Dockerfile
    depends_on:
      - server
    ports:
      - '8080:5000'
    networks:
      - chatnetwork

  client02:
    image: client
    container_name: client02
    depends_on:
      - server
      - client01
    ports:
      - '9000:5000'
    networks:
      - chatnetwork
