version: '3.9'

services:
  server:
    image: server
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - 8000:8000
    networks:
      - crypto

  client:
    image: client
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server
    ports:
      - '5000:5000'
    networks:
      - crypto


networks:
  crypto:
    driver: bridge